version: "3"

services:

  envoy:
    build:
      context: ./envoy
    ports:
      - 10000:10000
    networks:
      - demonet

  upstream:
    image: nginx
    networks:
      - demonet

networks:
  demonet: {}
